
networks:
        
        - ParticleEdge-Origin Full
          #- ParticleEdgeOk-Origin Full
        - ParticleEdge Full
          #- ParticleEdgeOk Full
        - ParticleNeXt (w/o SV) Full
          #- ParticleEdgeOk-SameVtx Full
          #- ParticleEdgeOk-SameVtx (w/o SV) Full
          - ParticleEdgeOk-Origin+SameVtx Full
          - ParticleEdgeOk (w/o SV) Full
          - ParticleEdgeOk-Origin (w/o SV) Full
          #- ParticleEdge-Origin+VtxDist+SameVtx Full
          #- ParticleNeXt Full
          #- ParticleNet
          #- ParticleEdge-Origin+SameVtx Full
          #- ParticleEdge-Origin+VtxDist+VtxCoord+SameVtx Full
