networks:
        - ParticleEdgeOk (w/o SV) Full
        - ParticleEdgeOk-Origin (w/o SV) Full
        - ParticleEdgeOk-SameVtx (w/o SV) Full
        - ParticleEdgeOk-Origin+VtxPos+SameVtx (w/o SV) Full
        - ParticleEdgeOk-Origin+VtxDist+SameVtx (w/o SV) Full
        - ParticleEdgeOk-Origin+SameVtx (w/o SV) Full
