## name of the directories where the various networks are saved.

networks:
        - ParticleEdge-Origin Full
        - ParticleEdge-SameVtx Full
        - ParticleEdge-Origin+VtxDist+VtxCoord+SameVtx Full
        - ParticleEdge-Origin+VtxDist+VtxCoord Full
        - ParticleEdge-VtxDist+VtxCoord Full
        - ParticleNeXt Full
        - ParticleEdge Full
        - ParticleNet
        - ParticleEdge-Origin+SameVtx Full
