## name of the directories where the various networks are saved.

networks:
        - ParticleEdgeOld-Origin Full
        - ParticleEdgeOld-SameVtx Full
        - ParticleEdgeOld-Origin+VtxPos+SameVtx Full
          #- ParticleEdgeOld-Origin+VtxDist+SameVtx Full
        - ParticleEdgeOld-Origin+SameVtx Full
        - ParticleEdgeOld Full
        - ParticleEdgeOld-VtxPos Full
          #- ParticleEdgeOld-Origin (aux saturation) Full
          #- ParticleEdgeOld-Origin+SameVtx (aux saturation) Full
          #- ParticleEdgeOld-Origin+VtxPos Full
