networks:
        - ParticleEdge-Origin Full
          # - ParticleEdge-Origin+VtxDist+VtxCoord+SameVtx Full
          #- ParticleEdge-Origin+VtxDist+VtxCoord Full
        - ParticleEdge-Origin+SameVtx Full
        - ParticleEdge-Origin+VtxDist+SameVtx Full
          # - ParticleEdge-Origin (w/o SV) Full
          # - ParticleEdge-Origin (aux saturation) Full
          #- ParticleEdge-Origin+SameVtx (aux saturation) Full
          #- ParticleNeXt (w/o SV)-Origin Full
          #- ParticleNeXt (w/o SV)-Origin+SameVtx Full
