networks:
        - ParticleEdgeOld-Origin Lite
        - ParticleEdgeOld Lite
        - ParticleNeXt (w/o SV) Lite
          #- ParticleEdgeOld-Origin+SameVtx Lite
        - ParticleNeXt Lite
        - ParticleNet
          #- ParticleEdge Lite
          #- ParticleEdge-Origin Lite
          #- ParticleEdge-SameVtx Lite
