
networks:

        - ParticleEdgeOld-Origin Full
          #- ParticleEdge-Origin Full
        - ParticleEdgeOld Full
          #- ParticleEdge Full
        - ParticleNeXt (w/o SV) Full
          #- ParticleEdge-SameVtx Full
          #- ParticleEdge-SameVtx (w/o SV) Full
          - ParticleEdge-Origin+SameVtx Full
          - ParticleEdge (w/o SV) Full
          - ParticleEdge-Origin (w/o SV) Full
          #- ParticleEdgeOld-Origin+VtxDist+SameVtx Full
          #- ParticleNeXt Full
          #- ParticleNet
          #- ParticleEdgeOld-Origin+SameVtx Full
          #- ParticleEdgeOld-Origin+VtxDist+VtxCoord+SameVtx Full
