networks:
        - ParticleNet
        - ParticleNeXt Full
        - ParticleEdge Full
        - ParticleEdge+Origin Full
        - ParticleEdge+SameVtx Full
        - ParticleEdge+Origin+SameVtx Full
        - ParticleEdge+Origin+VtxPos+SameVtx Full
        - ParticleEdge+Origin+VtxPos+SameVtx Full (aux saturation)

  (aux saturation)
        # - ParticleEdge+VtxPos Full
        # - ParticleEdge+Origin+VtxDist+SameVtx Full
