networks:
        - ParticleEdge Full
        - ParticleEdge-Origin Full
        - ParticleEdge-SameVtx Full
        - ParticleEdge-VtxPos Full
        - ParticleEdge-Origin+SameVtx Full
        - ParticleEdge-Origin+VtxPos+SameVtx Full
        - ParticleEdge-Origin+VtxDist+SameVtx Full
