## name of the directories where the various networks are saved.

networks:
        - ParticleEdgeOld-Origin (w/o SV) Full
        - ParticleNeXt (w/o SV) Full
        - ParticleEdgeOld (w/o SV) Full
        - ParticleNet (w/o SV)
        - ParticleEdge (w/o SV) Full
