## name of the directories where the various networks are saved.

networks:
        - ParticleEdgeOld-Origin Lite
        - ParticleEdgeOld-SameVtx Lite
        - TotAux Lite
        - ParticleEdgeOld-Origin+VtxDist+VtxCoord Lite
        - ParticleEdgeOld-VtxDist+VtxCoord Lite
        - ParticleNeXt Lite
        - ParticleEdgeOld Lite
        - ParticleNet
        - ParticleEdgeOld-Origin+SameVtx Lite
