## name of the directories where the various networks are saved.

networks:
        - ParticleEdgeOld-Origin Full
        - ParticleEdgeOld-SameVtx Full
        - ParticleEdgeOld-Origin+VtxDist+VtxCoord+SameVtx Full
        - ParticleEdgeOld-Origin+VtxDist+VtxCoord Full
        - ParticleEdgeOld-VtxDist+VtxCoord Full
        - ParticleNeXt Full
        - ParticleEdgeOld Full
        - ParticleNet
        - ParticleEdgeOld-Origin+SameVtx Full
